# Generated by Django 4.1.7 on 2023-03-21 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Authodication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bms_user_type',
            name='type_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Authodication.bms_roles'),
        ),
    ]
