# Generated by Django 4.1.7 on 2023-03-20 07:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=100)),
                ('created_role_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_role_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'role_tbl',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=150)),
                ('user_lname', models.CharField(max_length=150)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_password', models.CharField(max_length=150)),
                ('user_type', models.CharField(choices=[('A', 'Admin'), ('SA', 'Super Admin'), ('U', 'User')], max_length=150)),
                ('created_user_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_user_date', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.role')),
            ],
        ),
    ]
