# Generated by Django 4.1.7 on 2023-03-21 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authodication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bms_user_type',
            name='type_name',
        ),
        migrations.AddField(
            model_name='bms_user_type',
            name='type_name',
            field=models.ManyToManyField(blank=True, to='Authodication.bms_roles'),
        ),
    ]
