# Generated by Django 4.1.7 on 2023-03-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authodication', '0003_remove_bms_users_role_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bms_user_type',
            name='type_name',
            field=models.ManyToManyField(blank=True, related_name='song', to='Authodication.bms_roles'),
        ),
    ]
