# Generated by Django 4.1.7 on 2023-03-22 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authodication', '0005_alter_bms_users_user_type_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bms_user_type',
            name='type_name',
            field=models.ManyToManyField(blank=True, to='Authodication.bms_roles'),
        ),
        migrations.AlterField(
            model_name='bms_users',
            name='role_id',
            field=models.ManyToManyField(blank=True, related_name='song', to='Authodication.bms_roles'),
        ),
        migrations.AlterField(
            model_name='bms_users',
            name='user_type_id',
            field=models.ManyToManyField(blank=True, to='Authodication.bms_user_type'),
        ),
    ]
