# Generated by Django 4.1.7 on 2023-03-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=23)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(default='', max_length=200)),
                ('published', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
