# Generated by Django 4.1.7 on 2023-03-13 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_mobile_emp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emp',
        ),
        migrations.DeleteModel(
            name='Mobile',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
