# Generated by Django 4.1.7 on 2023-03-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.TextField(),
        ),
    ]
