# Generated by Django 4.1.7 on 2023-03-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authodication', '0004_alter_bms_user_type_type_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bms_users',
            name='user_type_id',
            field=models.ManyToManyField(blank=True, related_name='song', to='Authodication.bms_user_type'),
        ),
    ]
