# Generated by Django 4.1.7 on 2023-03-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authodication', '0007_alter_bms_users_user_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bms_users_details',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='bms_users_details',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bms_users_details',
            name='role_id',
            field=models.ManyToManyField(blank=True, related_name='xyz', to='Authodication.bms_roles'),
        ),
        migrations.AddField(
            model_name='bms_users_details',
            name='user_id',
            field=models.ManyToManyField(related_name='abc', to='Authodication.bms_users'),
        ),
    ]
