# Generated by Django 4.1.7 on 2023-03-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0002_alter_bms_access_control_rfid_master_user_id'),
        ('Authodication', '0010_remove_bms_users_details_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bms_users_details',
            name='department_id',
            field=models.ManyToManyField(related_name='dep', to='Device.bms_department_master'),
        ),
        migrations.AlterField(
            model_name='bms_users_details',
            name='locker_id',
            field=models.ManyToManyField(related_name='locker', to='Device.bms_locker'),
        ),
    ]
