# Generated by Django 4.1.7 on 2023-04-04 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authodication', '0013_bms_users_register_remove_bms_users_user_type_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bms_users_register',
            name='image',
        ),
    ]
