# Generated by Django 4.1.7 on 2023-04-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0002_alter_bms_access_control_rfid_master_user_id'),
        ('Authodication', '0014_remove_bms_users_register_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bms_users_register',
            name='department_id',
            field=models.ManyToManyField(to='Device.bms_department_master'),
        ),
        migrations.AddField(
            model_name='bms_users_register',
            name='locker_id',
            field=models.ManyToManyField(to='Device.bms_locker'),
        ),
    ]
