# Generated by Django 4.1.7 on 2023-04-04 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authodication', '0015_bms_users_register_department_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bms_users_details',
            name='image',
        ),
    ]
