# Generated by Django 4.1.7 on 2023-04-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authodication', '0016_remove_bms_users_details_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='bms_roles',
            name='module_id',
            field=models.ManyToManyField(to='Authodication.bms_module_master'),
        ),
    ]
