# Generated by Django 4.1.7 on 2023-04-04 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authodication', '0017_bms_roles_module_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bms_roles',
            old_name='module_id',
            new_name='permissions_id',
        ),
    ]
