# Generated by Django 4.1.7 on 2023-04-04 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authodication', '0019_alter_bms_roles_permissions_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bms_roles',
            name='permissions_id',
        ),
    ]
