# Generated by Django 4.1.7 on 2023-04-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authodication', '0020_remove_bms_roles_permissions_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bms_roles',
            name='permissions_id',
            field=models.ManyToManyField(related_name='dev', to='Authodication.bms_module_master'),
        ),
    ]
