# Generated by Django 4.1.7 on 2023-02-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consult',
            old_name='position',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='consult',
            old_name='group',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='describe',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='file',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='consult',
            name='update_date',
        ),
    ]
