# Generated by Django 4.1.7 on 2023-03-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0001_initial'),
        ('Authodication', '0003_remove_bms_users_role_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bms_users_details',
            name='department_id',
            field=models.ManyToManyField(blank=True, to='Device.bms_department_master'),
        ),
        migrations.AddField(
            model_name='bms_users_details',
            name='locker_id',
            field=models.ManyToManyField(blank=True, to='Device.bms_locker'),
        ),
        migrations.RemoveField(
            model_name='bms_users_details',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='bms_users_details',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bms_users_details',
            name='role_id',
            field=models.ManyToManyField(blank=True, to='Authodication.bms_roles'),
        ),
        migrations.AddField(
            model_name='bms_users_details',
            name='user_id',
            field=models.ManyToManyField(blank=True, to='Authodication.bms_users'),
        ),
    ]
