# Generated by Django 4.1.7 on 2023-03-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authodication', '0002_remove_bms_user_type_type_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bms_users',
            name='role_id',
        ),
        migrations.RemoveField(
            model_name='bms_users',
            name='user_type_id',
        ),
        migrations.AddField(
            model_name='bms_users',
            name='role_id',
            field=models.ManyToManyField(blank=True, to='Authodication.bms_roles'),
        ),
        migrations.AddField(
            model_name='bms_users',
            name='user_type_id',
            field=models.ManyToManyField(blank=True, to='Authodication.bms_user_type'),
        ),
    ]
