# Generated by Django 4.1.7 on 2023-03-22 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Device', '0001_initial'),
        ('Authodication', '0008_remove_bms_users_details_role_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bms_users_details',
            name='department_id',
            field=models.ManyToManyField(to='Device.bms_department_master'),
        ),
        migrations.AddField(
            model_name='bms_users_details',
            name='locker_id',
            field=models.ManyToManyField(to='Device.bms_locker'),
        ),
        migrations.AlterField(
            model_name='bms_user_type',
            name='type_name',
            field=models.ManyToManyField(blank=True, related_name='aaa', to='Authodication.bms_roles'),
        ),
    ]
