# Generated by Django 4.1.7 on 2023-03-03 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emplo',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.student')),
                ('phone', models.CharField(max_length=12)),
            ],
            bases=('api.student',),
        ),
        migrations.CreateModel(
            name='WEERE',
            fields=[
                ('student_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.student')),
                ('salary', models.CharField(max_length=12)),
            ],
            bases=('api.student',),
        ),
    ]
