# Generated by Django 4.1.7 on 2023-03-03 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_emplo_weere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qwe',
            fields=[
                ('emplo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.emplo')),
                ('asa', models.CharField(max_length=23)),
            ],
            bases=('api.emplo',),
        ),
    ]
