# Generated by Django 4.1.7 on 2023-03-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authodication', '0010_remove_bms_users_details_user_id_and_more'),
        ('Device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bms_access_control_rfid_master',
            name='user_id',
            field=models.ManyToManyField(to='Authodication.bms_users'),
        ),
    ]
