# Generated by Django 3.1.5 on 2022-09-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=300)),
                ('status', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=300)),
            ],
        ),
    ]
