# Generated by Django 3.1.5 on 2022-09-21 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserOpeartion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('N', 'Inactive')], max_length=300),
        ),
    ]
