# Generated by Django 3.1.5 on 2022-10-01 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserOpeartion', '0002_auto_20220921_1241'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee_table',
        ),
    ]
