# Generated by Django 4.1.7 on 2023-03-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authodication', '0004_bms_users_details_department_id_and_more'),
        ('Device', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bms_access_control_rfid_master',
            name='user_id',
            field=models.ManyToManyField(to='Authodication.bms_users'),
        ),
        migrations.AddField(
            model_name='bms_history',
            name='user_id',
            field=models.ManyToManyField(blank=True, to='Authodication.bms_users'),
        ),
        migrations.AddField(
            model_name='bms_settings',
            name='module_id',
            field=models.ManyToManyField(blank=True, to='Authodication.bms_module_master'),
        ),
    ]
