# Generated by Django 4.1.7 on 2023-03-13 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emp',
            table='emp_table',
        ),
    ]
