# Generated by Django 4.1.7 on 2023-03-13 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_emp_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
